### ISSUE TITLE
Error when fitting an example fit_ssm: Error in updateCholesky(L, hessian.random)

### ISSUE THREAD

**Issue by TobyDT** [ianjonsen/aniMotum#66]
I get the following error when fitting a fit_ssm() on any of 1) data it has previously worked on, 2) new data and 3) example data. I am using R 4.3.2 and aniMotum 1.2-06

Error in updateCholesky(L, hessian.random) : 
  function 'sexp_as_cholmod_sparse' not provided by package 'Matrix'
Error in rep$pdHess : $ operator is invalid for atomic vectors

This produced the issue:

fit <- fit_ssm(x = ellie, model = "rw", time.step = 24)

and get:

fitting rw SSM to 1 tracks...
 pars:   3.59133 3.45099 -2.91153      Error in nlminb(obj$par, ifelse(control$verbose == 1, myfn, obj$fn), obj$gr,  : 
  NA/NaN gradient evaluation

Error in updateCholesky(L, hessian.random) : 
  function 'sexp_as_cholmod_sparse' not provided by package 'Matrix'
Error in rep$pdHess : $ operator is invalid for atomic vectors

Windows 10
RStudio
R Version 4.3.2

**Comment by ianjonsen** [comment]
This is probably due to an incompatibility between `Matrix` & `TMB` pkg versions. It's an annoying issue that I don't have any control over! To resolve, I would update your `Matrix` pkg to the latest version on CRAN. Then, reinstall `TMB` from source:

`install.packages("TMB", type = "source", dependencies = TRUE)`

This builds `TMB` against your `Matrix` pkg version. Finally, you should reinstall `aniMotum` from source:

`install.packages("aniMotum", type = "source", repos = c("https://cloud.r-project.org",
                 "https://ianjonsen.r-universe.dev"), dependencies = TRUE)`

This ensures `aniMotum` is built against your `TMB` pkg version.

**Comment by TobyDT** [comment]
Thanks Ian! This worked in R 4.3.2 (Matrix 1.6-1.1; TMB 1.9.14; aniMotum 1.2-06) 

It didn't work for R 4.4.1 (Matrix 1.7-0) and it wasn't made in explicit in the error messaging but this was because I hadn't downloaded Rtools 4.4. After that it work in case anyone gets stuck with the same problem.

**Comment by ianjonsen** [comment]
Not certain why you couldn't build aniMotum from source on R 4.4.1 with Rtools 4.4. I can push a small update to R-universe later today, and once their platform builds the Windows binary it may be suitable for you to install (ie. to avoid building from source).
